### PR TITLE
Fix: warning about circular dependency

### LINKED ISSUE #18: Circular dependency warning
```
/app/vendor/bundle/ruby/2.2.0/gems/asyncapi-client-0.4.0/app/services/asyncapi/client/update_job.rb:4: warning: circular argument reference - job
/app/vendor/bundle/ruby/2.2.0/gems/asyncapi-client-0.4.0/app/services/asyncapi/client/update_job.rb:4: warning: circular argument reference - params
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.15/lib/active_support/dependencies.rb:247:in `require': cannot load such file -- pry (LoadError)
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.15/lib/active_support/dependencies.rb:247:in `block in require'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.15/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.1.15/lib/active_support/dependencies.rb:247:in `require'
	from /app/config/application.rb:33:in `block in <class:Application>'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/railtie.rb:224:in `call'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/railtie.rb:224:in `block in run_console_blocks'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/railtie.rb:245:in `each'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/railtie.rb:245:in `each_registered_block'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/railtie.rb:224:in `run_console_blocks'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/application.rb:421:in `run_console_blocks'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/engine.rb:434:in `load_console'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/commands/console.rb:51:in `initialize'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/commands/console.rb:9:in `new'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/commands/commands_tasks.rb:69:in `console'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/commands.rb:17:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/app_rails_loader.rb:43:in `require'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/app_rails_loader.rb:43:in `block in exec_app_rails'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/app_rails_loader.rb:32:in `loop'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/app_rails_loader.rb:32:in `exec_app_rails'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/lib/rails/cli.rb:5:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/bin/rails:9:in `require'
	from /app/vendor/bundle/ruby/2.2.0/gems/railties-4.1.15/bin/rails:9:in `<top (required)>'
	from bin/rails:16:in `load'
	from bin/rails:16:in `<main>'
```

### PR DESCRIPTION
**Pull request by ramontayag**
fix #18

Also convert changelog to http://keepachangelog.com/

### CODE REVIEW

File: app/services/asyncapi/client/update_job.rb [hunk 1]
```diff
@@ -1,7 +1,7 @@
 module Asyncapi::Client
   class UpdateJob
 
-    def self.execute(job: job, params: params)
```
Comment (jpmoral) [inline app/services/asyncapi/client/update_job.rb]: How did this work before?

Comment (ramontayag) [inline app/services/asyncapi/client/update_job.rb]: Ruby didn't care when it was the older version. Now it gives a warning
